### ISSUE TITLE
JOSS Review: Consider adding information about contributing and guidelines for doing so

### ISSUE THREAD

**Issue by gavinsimpson** [wilsoncai1992/DA.Test#15]
In order to clearly indicate how users can contribute to the development of the package and the guidelines for doing so, please consider adding a `CONTRIBUTING` (or `CONTRIBUTING.md`) file to the top level of the repo.

openjournals/joss-reviews/issues/161

**Comment by nhejazi** [comment]
This was completed by 089ff36, which, among other changes, added `CONTRIBUTING.md`
