### ISSUE TITLE
JOSS Review: Provide .Rmd source for the JOSS paper

### ISSUE THREAD

**Issue by gavinsimpson** [wilsoncai1992/DA.Test#18]
The Rmd or other source for the JOSS paper would be useful to see how the pkg was used in the simulated data example described in the JOSS paper. 

openjournals/joss-reviews#161

**Comment by nhejazi** [comment]
The JOSS paper had merely been written in markdown, with figures generated and added manually.  An Rmd file, which will contain R code for producing the figures, was added to the `paper` directory in a903762.
