### ISSUE TITLE
More concise package name

### ISSUE THREAD

**Issue by nhejazi** [wilsoncai1992/DA.Test#21]
While highly descriptive, the current name of the package is quite annoying/cumbersome to type. I would propose a change to a shorter (perhaps less descriptive) name. The following appear appropriate, though many other options are surely possible:

1. damt - __D__ : Data, __A__ : Adaptive, __M__ : Multiple, __T__ : Testing
2. ... (other ideas to come)

**Comment by wilsoncai1992** [comment]
DAda Test?

**Comment by wilsoncai1992** [comment]
brain storming here

**Comment by nhejazi** [comment]
Is there a part of "DAda Test" that I'm not getting? (what is the second "da" for?)

Based on that, "daTest" might be funny/amusing, with "da" obviously primarily being "data adaptive" but also just [as in](http://www.urbandictionary.com/define.php?term=DA) "THE only test you should use."

**Comment by wilsoncai1992** [comment]
I like DA Test.

**Comment by nhejazi** [comment]
sounds good to me

I was also going to suggest

1. testAdapt
2. multAdapt

**Comment by wilsoncai1992** [comment]
All seem nice! Go for it!

**Comment by nhejazi** [comment]
Oh -- I should have mentioned that I cannot change the repository name so you'll have to make a final decision and make the change (privileges for collaborators are not the same as for owners)

**Comment by wilsoncai1992** [comment]
Got it! Let’s do DA Test for the moment

**Comment by nhejazi** [comment]
`DAtest` sounds good to me -- go ahead and change the repo name when you have the chance

**Comment by nhejazi** [comment]
Oh, just saw you already did it -- perfect!
